### create account
POST http://localhost:8080/account
Content-Type: application/json

{
  "userId": 1,
  "initBalance": 1000
}

### delete account
DELETE http://localhost:8080/account
Content-Type: application/json

{
  "userId": 1,
  "accountNumber": "1000000002"
}

### get account
GET http://localhost:8080/account?user_id=1
