### use balance
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId":1,
  "accountNumber":"1000000002",
  "amount":100
}

### use balance2
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId":1,
  "accountNumber":"1000000002",
  "amount":100
}

### cancle balance
POST http://localhost:8080/transaction/cancel
Content-Type: application/json

{
  "transactionId":"5bfddb9fcbc4422383ad1bd4effa03c0",
  "accountNumber":"1000000002",
  "amount":20000
}

### query transaction
GET http://localhost:8080/transaction/153cd5595a7d4c5cbbb719a6cfeac612
Content-Type: application/json